# Generated by Django 6.0.2 on 2026-03-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_node_edge_riderequest_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='created_at',
        ),
        migrations.AddField(
            model_name='node',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
